apiVersion: v1
data:
  policy.csv: |
    p, role:readonly, applications,   get, */*, allow
    p, role:readonly, certificates,   get, *,   allow
    p, role:readonly, clusters,       get, *,   allow
    p, role:readonly, repositories,   get, *,   allow
    p, role:readonly, projects,       get, *,   allow
    p, role:readonly, accounts,       get, *,   allow
    p, role:readonly, gpgkeys,        get, *,   allow
    p, role:readonly, logs,           get, */*, allow

    p, role:admin, applications,    create,   */*, allow
    p, role:admin, applications,    update,   */*, allow
    p, role:admin, applications,    delete,   */*, allow
    p, role:admin, applications,    sync,     */*, allow
    p, role:admin, applications,    override, */*, allow
    p, role:admin, applications,    action/*, */*, allow
    p, role:admin, applicationsets, get,      */*, allow
    p, role:admin, applicationsets, create,   */*, allow
    p, role:admin, applicationsets, update,   */*, allow
    p, role:admin, applicationsets, delete,   */*, allow
    p, role:admin, certificates,    create,   *,   allow
    p, role:admin, certificates,    update,   *,   allow
    p, role:admin, certificates,    delete,   *,   allow
    p, role:admin, clusters,        create,   *,   allow
    p, role:admin, clusters,        update,   *,   allow
    p, role:admin, clusters,        delete,   *,   allow
    p, role:admin, repositories,    create,   *,   allow
    p, role:admin, repositories,    update,   *,   allow
    p, role:admin, repositories,    delete,   *,   allow
    p, role:admin, projects,        create,   *,   allow
    p, role:admin, projects,        update,   *,   allow
    p, role:admin, projects,        delete,   *,   allow
    p, role:admin, accounts,        update,   *,   allow
    p, role:admin, gpgkeys,         create,   *,   allow
    p, role:admin, gpgkeys,         delete,   *,   allow
    p, role:admin, exec,            create,   */*, allow

    g, role:admin,  role:readonly
    g, admin,       role:admin
    g, user_x,      role:admin
  policy.default: ""  # ^^^^ add more users just duplicating the line above and replacing g, <user>, role:<admin> e.g, user_y, role:admin
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.6.6
    helm.sh/chart: argo-cd-5.46.7
  name: argocd-rbac-cm
  namespace: argocd
