kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["create", "list", "get", "watch", "update", "delete", "patch"]
- apiGroups: ["extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
