kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-only
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
